### ISSUE TITLE
MPTCP support

### ISSUE THREAD

**Issue by GinesGarcia** [CoreSecurity/pcapy#15]
Hi,
can I manage mptcp options using pcapy?

thanks in advance,
Ginés.

**Comment by martinuy** [comment]
It looks like MPTCP is a higher level operating system network feature. For sure you can try to implement it in Python using Pcapy. But please keep in mind that Pcapy is a lower level tool for reading and injecting packets into a single network interface. This feature cannot be added to Pcapy.
