### ISSUE TITLE
pcapy on Python Package Index

### ISSUE THREAD

**Issue by mani-monaj** [CoreSecurity/pcapy#2]
Is there any plan to put version 0.10.8 on Python Package Index? The [current version](https://pypi.python.org/pypi/pcapy) on pypi is 0.10.3.

**Comment by core-ablanco** [comment]
Updated pcapy information on python package index.

> $ sudo pip install pcapy
> Downloading/unpacking pcapy
>   Downloading pcapy-0.10.8.tar.gz
>   Running setup.py (path:/tmp/pip_build_root/pcapy/setup.py) egg_info for package pcapy
> ...
> Successfully installed pcapy
> Cleaning up...
> $

**Comment by Yasumoto** [comment]
Wow, this is awesome- thank you!

**Comment by mani-monaj** [comment]
@core-ablanco That's great. Thank you.
