### ISSUE TITLE
Error loading shared library libpcap.so.1.3

### ISSUE THREAD

**Issue by smutt** [CoreSecurity/pcapy#20]
ImportError: Error loading shared library libpcap.so.1.3: No such file or directory (needed by /usr/lib/python2.7/site-packages/pcapy.so)

root@turris:/# uname -a
Linux turris 4.4.39-80079e1c1e5f9ca7ad734044462a761a-4 #1 SMP Fri Feb 10 09:50:47 CET 2017 armv7l n

root@turris:/usr/lib# ls -la |grep libpcap
lrwxrwxrwx    1 root     root            14 Feb 10 04:18 libpcap.so -> libpcap.so.1.8
lrwxrwxrwx    1 root     root            16 Feb 23 11:34 libpcap.so.1.3 -> libpcap.so.1.8.1
lrwxrwxrwx    1 root     root            16 Feb 10 04:18 libpcap.so.1.8 -> libpcap.so.1.8.1
-rw-r--r--    1 root     root        209672 Feb 10 04:18 libpcap.so.1.8.1

This is on a Turris Omnia which runs OpenWRT. It worked after I created the symbolic link above, but I don't think I should need to do that.

**Comment by smutt** [comment]
Ignore, this was just me being stupid.

**Comment by user2589** [comment]
@smutt ,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/SecureAuthCorp/pcapy/issues/20)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!
