### ISSUE TITLE
Export pcap_get_selectable_fd function

### ISSUE THREAD

**Issue by geekhckr** [CoreSecurity/pcapy#21]
Export pcap_get_selectable_fd, this is useful to use pcapy with external event loops.

**Comment by geekhckr** [comment]
Pull Request raised with the changes.
https://github.com/CoreSecurity/pcapy/pull/22

**Comment by user2589** [comment]
@geekhckr ,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/SecureAuthCorp/pcapy/issues/21)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!
