### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by lzkjyang** [CoreSecurity/pcapy#24]
setup at  py2.7   win7 64bit ,Visual C++ 9.0 for Python
  error:
ed in function "struct _object * __cdecl open_live(struct _object *,struct _obje
ct *)" (?open_live@@YAPEAU_object@@PEAU1@0@Z)
pcapy.obj : error LNK2019: unresolved external symbol pcap_open_live referenced
in function "struct _object * __cdecl open_live(struct _object *,struct _object
*)" (?open_live@@YAPEAU_object@@PEAU1@0@Z)
pcapy.obj : error LNK2019: unresolved external symbol pcap_lookupnet referenced
in function "struct _object * __cdecl open_live(struct _object *,struct _object
*)" (?open_live@@YAPEAU_object@@PEAU1@0@Z)
pcapy.obj : error LNK2019: unresolved external symbol pcap_open_offline referenc
ed in function "struct _object * __cdecl open_offline(struct _object *,struct _o
bject *)" (?open_offline@@YAPEAU_object@@PEAU1@0@Z)
pcapy.obj : error LNK2019: unresolved external symbol pcap_open_dead referenced
in function "struct _object * __cdecl bpf_compile(struct _object *,struct _objec
t *)" (?bpf_compile@@YAPEAU_object@@PEAU1@0@Z)
build\lib.win-amd64-2.7\pcapy.pyd : fatal error LNK1120: 26 unresolved externals

error: command 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Common\\Micr
osoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit st
atus 1120

**Comment by asolino** [comment]
Hey @lzkjyang 

You probably didn't download the WinPcap Developer's Pack and/or didn't modify the library_dirs variable in the pcapy ```setup.py``` file.

Please check our [wiki](https://github.com/CoreSecurity/pcapy/wiki/Compiling-Pcapy-on-Windows-Guide) and reopen this issue if it still not working

**Comment by user2589** [comment]
@lzkjyang ,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/SecureAuthCorp/pcapy/issues/24)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!
