### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by 3tarazona** [CoreSecurity/pcapy#27]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c pcapdumper.cc -o build/temp.linux-x86_64-2.7/pcapdumper.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
**pcapdumper.cc:11:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>**
                  ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by asolino** [comment]
Hey @3tarazona 

You need to have libpcap-dev or similar installed in your system.
