### ISSUE TITLE
help!!!when will the python3 version come out?

### ISSUE THREAD

**Issue by onewaymyway** [CoreSecurity/pcapy#3]
this code don't work on python3
will you guys work out the python3 version?
python3 has removed Py_FindMethod c api
so i can't compile it
i am a new python3 coder
i just can't fix it myself
can anybody help

**Comment by Congee** [comment]
Hey buddies, I've created a fork which implemented py3 support initialy. Would like to test ti?
https://github.com/Congee/pcapy

**Comment by jnthntatum** [comment]
I tested it and works pretty well :-) I rebased @Congee's changes off of core securities head and added a few tests if anyone wants to take a look. I spoke with @core-ablanco. He was open to testing / accepting the changes, but was unsure when there'd be time to do so.

https://github.com/jnthntatum/pcapy/tree/feature/python3-support
If anyone wants to take a look.

**Comment by dajose22** [comment]
I'm looking forward this python3 support!

**Comment by dajose22** [comment]
@core-ablanco any progress on checking this?

@jnthntatum maybe you can create a Pull request?

**Comment by anthraxx** [comment]
still no progress or any comment. feels like a pretty much dead project. that's really unfortunate

**Comment by dajose22** [comment]
please don't let this die.

I opened a pull request with @jnthntatum implementation. Is there something that is holding on the merge?

**Comment by core-ablanco** [comment]
Sorry for the delay but we don't have people assigned to this project. I will try to merge as soon as I can test the fork on Linux, Windows and OS X.

**Comment by anthraxx** [comment]
@core-ablanco that sounds great, thx. If everything looks fine it would be awesome to also get a new release version with python3 support. I'm looking forward to package this for a distribution :smiley:

**Comment by core-ablanco** [comment]
After testing that we where able to build the fork on Linux, OS X and Windows for both 2.7 and 3.5 Python versions we merged the pull request.

**Comment by dajose22** [comment]
Thanks! :+1: 

please don't forget to release the new version on pypi

**Comment by core-ablanco** [comment]
pypi has been updated.

**Comment by jnthntatum** [comment]
Awesome! Thanks @core-ablanco!

**Comment by dajose22** [comment]
thanks!!! :)
