### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by ybovard** [CoreSecurity/pcapy#37]
function next() seems to have a memory leak. The with the following code the memory increases through the time:
```
import pcapy

class PacketSniffer:
    def sniff(self):
        livecapture = pcapy.open_live('eth0', 65536, 1, 0)
        self._run=True
        while self._run:
            captured = livecapture.next()

if __name__ == '__main__':
  sniffer=PacketSniffer()
  sniffer.sniff()
```

OS: Red Hat Enterprise Linux Server release 7.3 (Maipo)

python: Python 3.5.1

pip show pcapy
```
Name: pcapy
Version: 0.11.1
Summary: Python pcap extension
Home-page: https://github.com/CoreSecurity/pcapy
Author: CORE Security
Author-email: oss@coresecurity.com
License: Apache modified
Location: /opt/python_virtualenv/ibn/lib/python3.5/site-packages
Requires:
```

**Comment by rp25** [comment]
OS: Win 10 Pro
Python: Python 3.6.1 |Anaconda custom (64-bit)

Name: pcapy
Version: 0.10.9
Summary: Python pcap extension
Home-page: https://github.com/CoreSecurity/pcapy
Author: CORE Security
Author-email: oss@coresecurity.com
License: Apache modified
Location: c:\programdata\anaconda3\lib\site-packages
Requires:

I'm having the same issue.

**Comment by jab1982** [comment]
Issue #12 was closed without a solution to this memory leak problem. https://github.com/CoreSecurity/pcapy/issues/12

**Comment by aouinizied** [comment]
Having the same issue.

**Comment by stamparm** [comment]
* This is still not fixed: `next()` leaks, while `loop()` doesn't (p.s. later found out that even the `sec, usec = header.getts()` inside the `loop()` defined handler causes leaks)
* Everything points to the conclusion that there is a leakage when accessing **wrapped object's attributes** (more accessing will cause more memory leakage) as can also be spotted inside the "failed" [fix](https://github.com/schischi/pcapy/commit/20a533f014344f25bc859fef016f2766af008fdc)
* Only Python3 is affected. Python2 works as expected
* Testing environment: Ubuntu 14.04, Python 3.4.3, pcapy 0.11.4 (from PyPI)
* `pmap` shows substantial memory leakage, depending on the amount of traffic that is being processed
* On a huge pipe you'll end with the silent kill (error code 143) pretty soon (e.g. 1.5MB/sec leakage on a filled 1Gbps traffic pipe)
* Even the simplest piece of code (https://github.com/stamparm/maltrail/issues/162#issuecomment-530791333) causes the leakage

**Comment by stamparm** [comment]
Dirty way around:

1) Use single `loop()` instead of multiple calls to `next()`
2) Instead of `sec, usec = header.getts()` inside the packet handler function use `sec, usec = [int(_) for _ in ("%.6f" % time.time()).split('.')]`

This way you'll minimize usage of leaking attribute access

**Comment by Avishay116** [comment]
Use pcapy 0.11.5.
The memory leak problem is solved in this version.
Note: this version is not yet on pypi, so download it from "releases" and install it manually. 

Good luck
