### ISSUE TITLE
pcap statistics

### ISSUE THREAD

**Issue by drakej** [CoreSecurity/pcapy#5]
It would be nice to have some sort of mechanism to find out if the kernel or network interface are dropping packets due to the ring buffer being full. This happens on busy interfaces and while I set the snap length low for the type of traffic I'm dealing with, to minimize how much each packet takes in the buffer, I would like some feedback from the software on if there is loss to mitigate the issue. 

tcpdump/pcap support this sort of information via [pcap_stats](http://www.tcpdump.org/manpages/pcap_stats.3pcap.html). It's also given via tcpdump when you exit a capture. 

E.G:
X packets captured
Y packets received by filter
Z packets dropped by kernel

**Comment by martinuy** [comment]
Support for stats has been added at 30b2f5d33806a58f692bd76a8a1952280d4dcde5 (thanks to @duggan contribution). I'll close this ticket.
