### ISSUE TITLE
'pcap.h' : No such file or directory

### ISSUE THREAD

**Issue by kamakazikamikaze** [CoreSecurity/pcapy#6]
Installing pcapy from `pip` or straight from source fails. Binary cannot be installed from your website because it won't accept anything *newer* than 2.7 (or at least 64-bit)

Installing via CMD.exe (Win7 64-bit) ends up with this line:

"pcapdumper.cc(11) : fatal error C1083: Cannot open include file: 'pcap.h': No such file or directory"

**Comment by core-ablanco** [comment]
I just updated the "Compiling Pcapy on Windows Guide", you can find it on the wiki.
